import Link from "next/link";
import { ArrowRight, MapPin, Plane, Compass, CalendarDays, Check } from "lucide-react";
import FAQAccordion from "@/components/FAQAccordion";
import DestinationCard from "@/components/DestinationCard";
import DestinationFlightSearch from "@/components/DestinationFlightSearch";
import DestinationDealLinks from "@/components/DestinationDealLinks";
import { relatedDestinations, type Destination } from "@/data/destinations";
import { destinationStructuredData, serializeStructuredData } from "@/utils/destination-seo";

export default function DestinationPage({ destination }: { destination: Destination }) {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeStructuredData(destinationStructuredData(destination)) }} />
    <section className="relative bg-dark text-white">
      <div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-cover bg-center opacity-20" style={{ backgroundImage: "url('/images/hero-travel.png')" }} />
      <div className="container-main relative py-10 sm:py-16">
        <nav aria-label="Breadcrumb" className="mb-9"><ol className="flex flex-wrap items-center gap-2 text-xs text-white/80"><li><Link href="/" className="hover:underline">Home</Link></li><li aria-hidden="true">/</li><li><Link href="/destinations" className="hover:underline">Destinations</Link></li><li aria-hidden="true">/</li><li aria-current="page">{destination.city}</li></ol></nav>
        <div className="grid items-center gap-8 lg:grid-cols-[1.6fr_1fr]">
          <div><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/80">Flights to {destination.city}</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-tight sm:text-5xl">{destination.heroTitle}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/85 sm:text-lg">{destination.heroDescription}</p><a href="#flight-search" className="mt-7 inline-flex items-center gap-3 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white transition hover:bg-white hover:text-dark focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">Search Flights to {destination.city}<ArrowRight aria-hidden="true" className="h-4 w-4" /></a></div>
          <div className="rounded-3xl border border-white/20 bg-white/5 p-6 backdrop-blur-sm"><Compass aria-hidden="true" className="mb-4 h-9 w-9 text-white/80" /><p className="text-xs uppercase tracking-widest text-white/70">Your destination guide</p><p className="mt-2 text-2xl font-black">{destination.city}</p><p className="mt-1 text-sm text-white/80">{destination.country}</p><div className="mt-5 flex flex-wrap gap-2">{destination.airportCodes.map((code) => <span key={code} className="rounded-lg bg-white/10 px-3 py-2 text-sm font-bold">{code}</span>)}</div><p className="mt-5 text-sm leading-6 text-white/75">Airport options, local highlights and practical planning in one place.</p></div>
        </div>
      </div>
    </section>
    <section className="section-padding"><div className="container-main grid gap-8 lg:grid-cols-[1.4fr_1fr]"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">A trip worth planning</p><h2 className="mt-2 text-3xl font-black text-dark">Travel to {destination.city}</h2><p className="mt-5 text-base leading-8 text-gray-600">{destination.introduction}</p></div><div className="rounded-2xl bg-light-blue p-6"><h2 className="flex items-center gap-2 text-lg font-black text-dark"><Plane aria-hidden="true" className="h-5 w-5 text-primary" />Flight planning tips</h2><ul className="mt-4 space-y-4">{destination.flightTips.map((tip) => <li key={tip} className="flex items-start gap-3 text-sm leading-6 text-gray-700"><Check aria-hidden="true" className="mt-1 h-4 w-4 shrink-0 text-primary" />{tip}</li>)}</ul></div></div></section>
    <section className="section-padding bg-slate-50"><div className="container-main"><DestinationFlightSearch city={destination.city} airportCode={destination.airportCodes[0]} routes={destination.popularRoutes} /></div></section>
    <section className="section-padding"><div className="container-main"><p className="text-xs font-bold uppercase tracking-widest text-primary">Arrival planning</p><h2 className="mt-2 text-3xl font-black text-dark">Airports Serving {destination.city}</h2><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{destination.airports.map((airport) => <article key={airport.code} className="flex flex-col rounded-2xl border border-gray-200 p-6"><div className="flex items-center gap-3"><span className="rounded-lg bg-light-blue px-3 py-2 text-sm font-black text-primary">{airport.code}</span><MapPin aria-hidden="true" className="h-5 w-5 text-primary" /></div><h3 className="mt-4 text-lg font-bold text-dark">{airport.name}</h3><p className="mt-3 flex-1 text-sm leading-7 text-gray-600">{airport.description}</p><a href={airport.source} className="mt-4 text-sm font-bold text-primary underline underline-offset-4">Official {airport.code} airport information</a></article>)}</div><p className="mt-4 text-xs leading-6 text-gray-500">Airport and transport details may change. Check official airport information before travelling.</p></div></section>
    <section className="section-padding bg-light-blue"><div className="container-main"><h2 className="flex items-start gap-3 text-3xl font-black text-dark"><CalendarDays aria-hidden="true" className="mt-1 h-7 w-7 shrink-0 text-primary" />Best Time to Visit {destination.city}</h2><p className="mt-5 max-w-3xl text-base leading-8 text-gray-600">{destination.bestTimeToVisit}</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{destination.travelSeasons.map((season) => <article key={season.name} className="rounded-2xl bg-white p-5"><h3 className="font-bold text-dark">{season.name}</h3><p className="mt-3 text-sm leading-7 text-gray-600">{season.description}</p></article>)}</div><p className="mt-4 text-xs text-gray-500">Seasonal guidance is general; weather varies and does not predict airfare.</p></div></section>
    <section className="section-padding"><div className="container-main"><h2 className="text-3xl font-black text-dark">Things to Do in {destination.city}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{destination.thingsToDo.map((highlight, index) => <article key={highlight.title} className="rounded-2xl border border-gray-200 p-6"><span className="text-sm font-black text-primary">0{index + 1}</span><h3 className="mt-4 text-lg font-bold text-dark">{highlight.title}</h3><p className="mt-3 text-sm leading-7 text-gray-600">{highlight.description}</p></article>)}</div></div></section>
    <section className="section-padding bg-slate-50"><div className="container-main grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-black text-dark">Things to Know Before You Fly</h2><p className="mt-5 text-base leading-8 text-gray-600">A little planning gives you more time to enjoy {destination.city}. Consider the airport transfer, the season and any fixed reservations together with your flight dates.</p><Link href="/contact" className="mt-5 inline-flex items-center gap-2 font-bold text-primary">Get help planning your {destination.city} trip<ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div><div className="rounded-2xl border border-gray-200 bg-white p-6"><h3 className="text-xl font-black text-dark">Travel Tips for {destination.city}</h3><ul className="mt-5 space-y-4">{destination.travelTips.map((tip) => <li key={tip} className="flex items-start gap-3 text-sm leading-7 text-gray-600"><Check aria-hidden="true" className="mt-1 h-4 w-4 shrink-0 text-primary" />{tip}</li>)}</ul></div></div></section>
    <section className="section-padding"><div className="container-main max-w-4xl"><h2 className="text-center text-3xl font-black text-dark">Flights to {destination.city}: Your Questions</h2><div className="mt-8 space-y-3"><FAQAccordion faqs={destination.faq} /></div></div></section>
    <section className="bg-dark py-12 text-white"><div className="container-main flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-2xl font-black sm:text-3xl">Ready to Explore {destination.city}?</h2><p className="mt-3 text-sm text-white/80">Start with airport options and travel dates that fit your plans.</p></div><a href="#flight-search" className="inline-flex shrink-0 items-center gap-3 rounded-xl bg-primary px-5 py-3 text-sm font-bold transition hover:bg-white hover:text-dark">Search Flights to {destination.city}<ArrowRight aria-hidden="true" className="h-4 w-4" /></a></div></section>
    <section className="section-padding"><div className="container-main"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-3xl font-black text-dark">Explore More Destinations</h2><Link href="/destinations" className="text-sm font-bold text-primary">View all destination guides →</Link></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{relatedDestinations(destination).map((item) => <DestinationCard key={item.slug} destination={item} />)}</div></div></section>
    <DestinationDealLinks city={destination.city} country={destination.country} />
  </>;
}
