import Link from "next/link";
import DealCard from "@/components/DealCard";
import RouteDealCard from "@/components/RouteDealCard";
import { dealCategories, routeDeals } from "@/data/deals";

export default function FlightDeals() {
  const featured = dealCategories.filter((category) => ["cheap-domestic-flights", "cheap-international-flights", "last-minute-flights"].includes(category.id));
  const premium = dealCategories.filter((category) => category.tone === "premium");
  const tripTypes = dealCategories.filter((category) => category.path.startsWith("/deals/"));
  return <>
    <section className="section-padding"><div className="container-main"><p className="text-xs font-bold uppercase tracking-widest text-primary">Choose a starting point</p><h2 className="mt-2 text-3xl font-black text-dark">Featured Deals & Planning Guides</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-gray-600">Explore a useful collection for your next journey. These are informational guides, not verified promotions or live fare offers.</p><div className="mt-7 grid gap-5 md:grid-cols-3">{featured.map((deal) => <DealCard key={deal.id} deal={deal} />)}</div></div></section>
    <section id="popular-routes" className="section-padding bg-slate-50"><div className="container-main"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-widest text-primary">Route inspiration</p><h2 className="mt-2 text-3xl font-black text-dark">Popular Routes</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-gray-600">Explore city pairs already featured on EasyFareBooking. Open a guide to start with the right airports, without a claim of direct service or availability.</p></div><div className="flex flex-wrap items-center justify-between gap-4"><h3 className="text-2xl font-black text-dark">Domestic Flight Deals</h3><Link href="/domestic-flight-deals" className="text-sm font-bold text-primary">Explore U.S. planning →</Link></div><p className="mt-4 text-sm leading-7 text-gray-600">City pairs for visits, weekends and work travel within the United States.</p><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{routeDeals.filter((route) => route.kind === "domestic").map((route) => <RouteDealCard key={route.slug} route={route} />)}</div></div></section>
    <section className="section-padding"><div className="container-main"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-3xl font-black text-dark">International Flight Deals</h2><Link href="/international-flight-deals" className="text-sm font-bold text-primary">Explore overseas planning →</Link></div><p className="mt-4 text-sm leading-7 text-gray-600">Plan the complete journey across borders, including airport choices and calendar arrival dates.</p><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{routeDeals.filter((route) => route.kind === "international").map((route) => <RouteDealCard key={route.slug} route={route} />)}</div></div></section>
    <section className="section-padding bg-light-blue"><div className="container-main"><h2 className="mb-7 text-3xl font-black text-dark">Cabin Choices Worth Understanding</h2><div className="grid gap-5 md:grid-cols-2">{premium.map((deal) => <DealCard key={deal.id} deal={deal} />)}</div></div></section>
    <section className="section-padding"><div className="container-main"><h2 className="mb-7 text-3xl font-black text-dark">A Journey That Fits Your Plans</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{tripTypes.map((deal) => <DealCard key={deal.id} deal={deal} />)}</div></div></section>
  </>;
}
