import Link from "next/link";
import { ArrowRight, BedDouble, Ship, Car, Check, Phone } from "lucide-react";
import { appData } from "@/data";
import { formatPhoneNumber } from "@/utils/helper";
import { services, type ServiceKind } from "@/data/services";
import { destinationPath, getDestinationByCity } from "@/data/destinations";
import FAQAccordion from "@/components/FAQAccordion";
import ServiceInquiryForm from "@/components/ServiceInquiryForm";
import ServiceHeroVisual from "@/components/ServiceHeroVisual";

const themes = {
  hotels: { surface: "bg-[#faf6ef]", accent: "bg-[#ede2d2]", subtitle: "A little comfort, wherever you land", formLabel: "Plan Your Stay", collectionIcons: [BedDouble, BedDouble, BedDouble, BedDouble] },
  cruise: { surface: "bg-light-blue", accent: "bg-primary/10", subtitle: "New horizons, a considered itinerary", formLabel: "Plan Your Cruise", collectionIcons: [Ship, Ship, Ship, Ship] },
  "car-rental": { surface: "bg-slate-50", accent: "bg-green/10", subtitle: "The freedom to travel at your own pace", formLabel: "Plan Your Rental", collectionIcons: [Car, Car, Car, Car, Car] },
};

export default function ServiceLandingPage({ service }: { service: ServiceKind }) {
  const config = services[service];
  const theme = themes[service];
  const destinations = ["New York", "London", "Paris", "Tokyo"].map(getDestinationByCity).filter((item) => item !== undefined);
  return <>
    <section className={`relative ${theme.surface}`}>
      <div className="container-main py-10 sm:py-14">
        <nav aria-label="Breadcrumb" className="mb-9"><ol className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><li><Link href="/" className="hover:text-primary hover:underline">Home</Link></li><li aria-hidden="true">/</li><li aria-current="page">{config.label}</li></ol></nav>
        <div className="grid items-center gap-8 lg:grid-cols-[1.12fr_1fr]">
          <div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">{config.label} planning</p><h1 className="mt-4 text-4xl font-black leading-tight tracking-tight text-dark sm:text-5xl">{config.title}</h1><p className="mt-5 max-w-xl text-base leading-8 text-slate-600">{config.description}</p><a href="#service-inquiry" className="mt-7 inline-flex items-center gap-3 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white transition hover:bg-dark focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{theme.formLabel}<ArrowRight aria-hidden="true" className="h-4 w-4" /></a><p className="mt-4 text-xs leading-6 text-slate-500">Planning inquiries · no live inventory or confirmed bookings</p></div>
          <div className="min-w-0 rounded-[32px] border border-white/70 bg-white/40 p-3 shadow-xl shadow-dark/5"><ServiceHeroVisual service={service} /><p className="px-4 py-4 text-sm font-semibold text-dark">{theme.subtitle}</p></div>
        </div>
      </div>
    </section>
    <section className="section-padding"><div className="container-main grid items-start gap-8 lg:grid-cols-[0.8fr_1.2fr]">
      <div><p className="text-xs font-bold uppercase tracking-widest text-primary">A useful starting point</p><h2 className="mt-3 text-3xl font-black text-dark">Your preferences.<br />A clearer conversation.</h2><p className="mt-5 text-sm leading-7 text-slate-600">A few details help shape the next step. Use the form to prepare an inquiry, then review it on Contact before choosing whether to send an email.</p><ol className="mt-7 space-y-5">{["Tell us what you have in mind", "Review the request on Contact", "Open and send a draft in your email app"].map((step, index) => <li key={step} className="flex items-start gap-3 text-sm leading-6 text-slate-700"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-black text-dark ${theme.accent}`}>{index + 1}</span><span className="pt-1">{step}</span></li>)}</ol><p className="mt-6 text-xs leading-6 text-slate-500">No request is sent by this website. A provider must confirm any real arrangement, price and terms.</p></div>
      <ServiceInquiryForm key={service} service={service} />
    </div></section>
    {service === "hotels" && <section className={`section-padding ${theme.surface}`}><div className="container-main"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-3xl font-black text-dark">Popular Destinations for Your Next Stay</h2><Link href="/destinations" className="text-sm font-bold text-primary">Explore all destination guides →</Link></div><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-600">Start with the city you want to explore. These are destination-planning guides, not hotel listings or availability claims.</p><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{destinations.map((destination) => <Link key={destination.slug} href={destinationPath(destination)} className="group flex flex-col rounded-2xl border border-white bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg motion-reduce:transform-none"><p className="text-xs text-slate-500">{destination.country}</p><h3 className="mt-2 text-xl font-black text-dark">{destination.city}</h3><p className="mt-3 flex-1 text-sm leading-7 text-slate-600">{destination.heroDescription}</p><span className="mt-5 flex items-center justify-between gap-2 text-sm font-bold text-primary">Plan your visit<ArrowRight aria-hidden="true" className="h-4 w-4 shrink-0 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></div></section>}
    <section className={`section-padding ${service === "hotels" ? "bg-white" : theme.surface}`}><div className="container-main"><p className="text-xs font-bold uppercase tracking-widest text-primary">{service === "cruise" ? "Regions to explore" : "Preferences, not inventory"}</p><h2 className="mt-3 text-3xl font-black text-dark">{config.collectionsTitle}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{config.collections.map((card, index) => { const Icon = theme.collectionIcons[index]; return <article key={card.title} className="flex min-w-0 flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:shadow-md motion-reduce:transform-none"><span className={`flex h-11 w-11 items-center justify-center rounded-xl text-primary ${theme.accent}`}><Icon aria-hidden="true" className="h-5 w-5" /></span><h3 className="mt-5 text-xl font-black text-dark">{card.title}</h3><p className="mt-3 flex-1 text-sm leading-7 text-slate-600">{card.description}</p><a href="#service-inquiry" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Discuss {card.title.toLowerCase()}<ArrowRight aria-hidden="true" className="h-4 w-4" /></a></article>; })}</div></div></section>
    <section className={`section-padding ${service === "hotels" ? theme.surface : "bg-white"}`}><div className="container-main"><h2 className="text-3xl font-black text-dark">{config.benefitsTitle}</h2><div className="mt-7 grid gap-6 md:grid-cols-3">{config.benefits.map((benefit) => <article key={benefit.title} className="rounded-2xl border border-slate-200 bg-white p-6"><Check aria-hidden="true" className="h-5 w-5 text-primary" /><h3 className="mt-4 text-lg font-black text-dark">{benefit.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{benefit.description}</p></article>)}</div></div></section>
    <section className="section-padding bg-dark text-white"><div className="container-main grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-white/65">Before you decide</p><h2 className="mt-3 text-3xl font-black">{config.tipsTitle}</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/75">Use your preferences as a starting point, then check the actual provider's details before committing to a booking.</p></div><ul className="space-y-4">{config.tips.map((tip) => <li key={tip} className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-7 text-white/85"><Check aria-hidden="true" className="mt-1 h-4 w-4 shrink-0 text-white/75" />{tip}</li>)}</ul></div></section>
    <section className="section-padding"><div className="container-main max-w-4xl"><h2 className="mb-8 text-center text-3xl font-black text-dark">Frequently Asked Questions</h2><div className="space-y-3"><FAQAccordion faqs={config.faq} /></div></div></section>
    <section className={`py-12 ${theme.surface}`}><div className="container-main flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-2xl font-black text-dark">Let's Make Your Travel Plans Clearer</h2><p className="mt-3 text-sm leading-7 text-slate-600">Prepare an inquiry or speak with us about your preferences.</p></div><div className="flex flex-wrap gap-3"><a href="#service-inquiry" className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white hover:bg-dark">{service === "hotels" ? "Stay Inquiry" : service === "cruise" ? "Cruise Inquiry" : "Rental Inquiry"}<ArrowRight aria-hidden="true" className="h-4 w-4" /></a><Link href={`/contact?service=${service}`} className="rounded-xl border border-primary/20 bg-white px-5 py-3 text-sm font-bold text-primary">Contact Us</Link></div></div><div className="container-main mt-5"><a href={`tel:+${appData.phoneNumber}`} className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><Phone aria-hidden="true" className="h-4 w-4" />{formatPhoneNumber(appData.phoneNumber)}</a></div></section>
  </>;
}
